// Bare-metal tiled NVFP4 linear layer on the NVFP4 RoCC accelerator (custom0).
//
// nvfp4_gemm.c proves one 4x16 output tile with K <= 256 -- i.e. exactly one
// COMPUTE's worth of work. This file is the next tier: a REAL full-size linear
// layer, M=4 N=256 K=2048, which is 16 output tiles wide and 8 K-chunks deep,
// so it cannot be expressed without tiling in both directions. It is the first
// thing in this chain that exercises the accelerator as an accelerator rather
// than as a single-instruction unit.
//
// What forces the tiling (all three are real RTL limits, see
// generators/nvfp4/src/main/scala/nvfp4/NVFP4Accel.scala):
//
//   * The array is mPE=4 by nPE=16. One COMPUTE produces one 4x16 tile.
//     A_rows > 4 or B_rows > 16 is clamped and sets a sticky error bit, so
//     N=256 must be walked 16 columns at a time.
//   * maxKBlocks = 16: at most 16 blocks of 16 elements, K <= 256, per
//     COMPUTE. K=2048 is 128 blocks, so it must be issued as 8 chunks.
//   * There is exactly ONE accumulator tile (the array's own registers;
//     acc_addr is accepted and ignored). So the N loop has to be the OUTER
//     loop: an output tile must be finished and drained before the next one
//     starts. Chunking K inside it is what COMPUTE_ACC is for.
//
// Why chunking K is legal and not an approximation: design doc section 3.3.
// Every term entering the accumulator is an exact integer (section 0: every
// E2M1 magnitude is a multiple of 1/2, so 2|x| is an integer and a 16-element
// block sum is an exact 13-bit integer) and the accumulator is plain
// two's-complement addition at a fixed LSB of 2^-20 (section 3.4). Integer
// addition is associative, so WHERE K is split cannot change one bit of the
// answer. That is why this kernel compares against the same exact golden
// accumulators a single-shot engine would have to produce, with NO tolerance.
// nvfp4_gemm.c's header argues this at length and it is not weakened here:
// max_abs_err is 0 on a pass, full stop. A nonzero value is a hardware bug.
//
// Issue sequence follows design doc section 4.4; layout follows section 4.5
// R1-R10. MVOUT (funct7 9) is deliberately never issued -- it is not
// implemented in RTL v1 and would only set the sticky "unimplemented" bit.
// MVOUT_RAW (funct7 10) is the exact, convention-free drain.
//
// This binary is built and disassembled here; the VCS/Verilator run is done
// separately.

#include <stdint.h>
#include <stdio.h>
#include <stddef.h>

#include "nvfp4.h"

// Machine-generated by a separate tool. Defines LAYER_M/N/K/KBLOCKS, the four
// A/B planes, the two weight_scale_2 fp32 bit patterns, and layer_acc -- the
// exact int64 golden accumulators with LSB 2^-20, i.e. precisely what
// MVOUT_RAW must return.
#include "nvfp4_layer_data.h"

// ---------------------------------------------------------------------------
// Compile-time checks on the data contract
// ---------------------------------------------------------------------------
// Cheap, and they turn a silently-wrong tiling into a build failure. The
// typedef trick rather than _Static_assert keeps this strictly -std=gnu99.
#define NVFP4_CT_ASSERT(cond, name) \
  typedef char nvfp4_ct_assert_##name[(cond) ? 1 : -1]

// ---------------------------------------------------------------------------
// Hardware shape (NVFP4Config defaults: mPE=4, nPE=16, maxKBlocks=16)
// ---------------------------------------------------------------------------
#define NVFP4_M_PE          4
#define NVFP4_N_PE          16
#define NVFP4_MAX_KBLOCKS   16

// One COMPUTE consumes a full scratchpad's worth of K. At the defaults the A
// scratchpad is mPE*maxKBlocks = 64 words and the B scratchpad is
// nPE*maxKBlocks = 256 words, and a 4-row / 16-row tile of 16 blocks fills
// each exactly -- indices run 0..63 and 0..255, one short of capacity. Asking
// for more blocks would be clamped and would set errSpad.
#define KB_PER_COMPUTE      NVFP4_MAX_KBLOCKS            // 16 blocks = 256 elems
#define K_CHUNKS            (LAYER_KBLOCKS / KB_PER_COMPUTE)   // 8
#define N_TILES             (LAYER_N / NVFP4_N_PE)             // 16

NVFP4_CT_ASSERT(LAYER_KBLOCKS == LAYER_K / NVFP4_BLOCK_K,       kblocks);
NVFP4_CT_ASSERT(LAYER_M == NVFP4_M_PE,                          m_fits_array);
NVFP4_CT_ASSERT(LAYER_N % NVFP4_N_PE == 0,                      n_divides);
NVFP4_CT_ASSERT(LAYER_KBLOCKS % KB_PER_COMPUTE == 0,            k_divides);
NVFP4_CT_ASSERT(KB_PER_COMPUTE <= NVFP4_MAX_KBLOCKS,            kb_fits);

// ---------------------------------------------------------------------------
// Layout arithmetic -- derived from section 4.5 R1/R2/R4/R5, not assumed
// ---------------------------------------------------------------------------
// R4: A is [M][K] row-major, K contiguous, two nibbles per byte, so a data row
// is K/2 bytes. Its scales are [M][K/16] uint8, so a scale row is K/16 bytes.
// R5: B is [N][K] with the identical shape, N being the output feature index.
//
//   LAYER_K = 2048  ->  data row  = 1024 bytes
//                       scale row =  128 bytes  (= LAYER_KBLOCKS)
//
// THE ROW STRIDES ARE THE FULL-ROW STRIDES FOR EVERY CHUNK. A K-chunk is a
// set of *columns* of the same matrix, not a separate matrix: rows are still
// LAYER_K/2 bytes apart in DRAM. Halving a stride along with the base pointer
// would make the DMA walk chunk c of row 0 and then chunk c-1 of row 1. Only
// the base pointers move. (nvfp4_gemm.c's K-split says the same thing; this is
// the same trap at 8 chunks instead of 2.)
#define A_DATA_ROW_STRIDE   (LAYER_K / 2)     // 1024 bytes
#define A_SCALE_ROW_STRIDE  (LAYER_K / 16)    //  128 bytes
#define B_DATA_ROW_STRIDE   (LAYER_K / 2)     // 1024 bytes
#define B_SCALE_ROW_STRIDE  (LAYER_K / 16)    //  128 bytes

// Chunk c covers elements [c*KB_PER_COMPUTE*16, (c+1)*KB_PER_COMPUTE*16) of
// every row.
//   data  : 2 elements per byte           -> c * 16*16/2 = c * 128 bytes
//   scales: 1 byte per 16-element block   -> c * 16      = c *  16 bytes
// Equivalently, 16 blocks are 16 eight-byte data words = 128 bytes, which is
// the "c*16*8" form. Both readings agree.
#define CHUNK_DATA_BYTES    (KB_PER_COMPUTE * NVFP4_BLOCK_K / 2)  // 128
#define CHUNK_SCALE_BYTES   (KB_PER_COMPUTE)                      //  16

// N-tile n0 is rows [n0, n0+16) of B, and B rows are contiguous:
//   data  : n0 * (LAYER_K/2)  bytes
//   scales: n0 * (LAYER_K/16) bytes
#define B_TILE_DATA_OFF(n0)   ((size_t)(n0) * B_DATA_ROW_STRIDE)
#define B_TILE_SCALE_OFF(n0)  ((size_t)(n0) * B_SCALE_ROW_STRIDE)

// R8 alignment check on every base this kernel forms. Data bases are
//   layer_a_data + c*128                        -> 128 | offset, so 64 | offset
//   layer_b_data + n0*1024 + c*128              -> 64 | offset
// and scale bases are offset by multiples of 16 and 128, so 8 | offset. Both
// hold provided the generated arrays are themselves aligned, which is the
// generator's half of the contract.
NVFP4_CT_ASSERT(CHUNK_DATA_BYTES % 64 == 0,    chunk_data_align);
NVFP4_CT_ASSERT(B_DATA_ROW_STRIDE % 64 == 0,   b_row_align);
NVFP4_CT_ASSERT(CHUNK_SCALE_BYTES % 8 == 0,    chunk_scale_align);
NVFP4_CT_ASSERT(B_SCALE_ROW_STRIDE % 8 == 0,   b_scale_row_align);

// ---------------------------------------------------------------------------
// Scratchpad / accumulator addresses
// ---------------------------------------------------------------------------
// A and B have separate scratchpad memories, so both tiles sit at base 0.
// B_SPAD is pinned rather than moved because COMPUTE does not encode a B
// scratchpad address at all (the "KNOWN GAP" note in nvfp4.h); the RTL uses
// whatever base the last MVIN_B wrote. Every chunk therefore reloads both
// tiles over the same bases, which is safe because cmd.ready is asserted only
// in sIdle -- a following MVIN physically cannot dequeue while a COMPUTE is
// still streaming.
#define A_SPAD ((nvfp4_addr_t)0)
#define B_SPAD ((nvfp4_addr_t)0)
#define ACC0   ((nvfp4_addr_t)0)

// ---------------------------------------------------------------------------
// Buffers
// ---------------------------------------------------------------------------
// MVOUT_RAW destination, the full [LAYER_M][LAYER_N] result. 8 bytes per
// element. Each tile writes a 4x16 sub-rectangle of it, which is expressible
// only because CONFIG_ST carries a destination row stride: set it to
// LAYER_N*8 and the engine advances LAYER_N*8 bytes between the tile's rows,
// dropping row m of the tile at &out[m*LAYER_N + n0].
static int64_t layer_out[LAYER_M * LAYER_N] __attribute__((aligned(64)));

// Per-output-tile accelerator-busy cycles, collected during the dispatch and
// printed afterwards so the printf cost stays out of the wall total.
static uint64_t tile_busy[N_TILES];

static double max_abs_err = 0.0;
static double max_rel_err = 0.0;
static int n_compared = 0;
static int n_mismatch = 0;

static inline uint64_t rdcycle(void) {
  uint64_t c;
  asm volatile("rdcycle %0" : "=r"(c));
  return c;
}

// ---------------------------------------------------------------------------
// One output tile: columns [n0, n0+16) of C, all of K
// ---------------------------------------------------------------------------
// Chunk 0 uses COMPUTE, which clears the accumulator tile; chunks 1..7 use
// COMPUTE_ACC, which adds into it. There is no separate clear instruction, so
// the first-chunk COMPUTE is load-bearing, not stylistic.
static void run_tile(int n0) {
  const uint8_t *const b_data_tile  = &layer_b_data [B_TILE_DATA_OFF(n0)];
  const uint8_t *const b_scale_tile = &layer_b_scale[B_TILE_SCALE_OFF(n0)];

  for (int c = 0; c < K_CHUNKS; c++) {
    const uint8_t *const a_d = &layer_a_data [(size_t)c * CHUNK_DATA_BYTES];
    const uint8_t *const a_s = &layer_a_scale[(size_t)c * CHUNK_SCALE_BYTES];
    const uint8_t *const b_d = &b_data_tile  [(size_t)c * CHUNK_DATA_BYTES];
    const uint8_t *const b_s = &b_scale_tile [(size_t)c * CHUNK_SCALE_BYTES];

    // Only the scale-plane base needs a CONFIG; the data-plane base is the
    // MVIN's own rs1. Strides stay full-row (see the derivation above).
    nvfp4_config_ld_a(A_DATA_ROW_STRIDE, A_SCALE_ROW_STRIDE, a_s);
    nvfp4_config_ld_b(B_DATA_ROW_STRIDE, B_SCALE_ROW_STRIDE, b_s);

    nvfp4_mvin_a(a_d, A_SPAD, LAYER_M, KB_PER_COMPUTE);
    nvfp4_mvin_b(b_d, B_SPAD, NVFP4_N_PE, KB_PER_COMPUTE);

    if (c == 0) {
      nvfp4_compute(A_SPAD, LAYER_M, KB_PER_COMPUTE,
                    NVFP4_N_PE, KB_PER_COMPUTE, ACC0);
    } else {
      nvfp4_compute_acc(A_SPAD, LAYER_M, KB_PER_COMPUTE,
                        NVFP4_N_PE, KB_PER_COMPUTE, ACC0);
    }
  }

  // Drain the finished 4x16 tile straight into its place in the [M][N] buffer.
  nvfp4_mvout_raw(&layer_out[n0], ACC0, LAYER_M, NVFP4_N_PE);
  nvfp4_flush(0);
}

// ---------------------------------------------------------------------------
// Exact integer compare -- no tolerance, ever
// ---------------------------------------------------------------------------
// See the file header and nvfp4_gemm.c's. The reported numbers are in RAW
// ACCUMULATOR LSB UNITS (1 LSB = 2^-20 of the pre-global-scale result), so a
// nonzero max_abs_err is a whole number of accumulator ticks and is a bug.
static void check_all(void) {
  for (int m = 0; m < LAYER_M; m++) {
    for (int n = 0; n < LAYER_N; n++) {
      const int idx = m * LAYER_N + n;
      const int64_t got  = layer_out[idx];
      const int64_t want = layer_acc[idx];

      // Two's-complement subtraction in uint64 gives the exact magnitude for
      // either ordering, with no signed overflow.
      const uint64_t ug = (uint64_t)got;
      const uint64_t uw = (uint64_t)want;
      const uint64_t d  = (got >= want) ? (ug - uw) : (uw - ug);

      if (d != 0) {
        if (n_mismatch < 8) {
          // newlib-nano has NO long long support: %llx silently prints the
          // bare "lx" tail. unsigned long is 64-bit on rv64 lp64d, so these
          // casts are the whole fix.
          printf("nvfp4_layer: MISMATCH at [%d][%d]: got 0x%016lx "
                 "want 0x%016lx\n",
                 m, n, (unsigned long)ug, (unsigned long)uw);
        }
        n_mismatch++;
      }

      const double ad = (double)d;
      const double aw = (want < 0) ? -(double)want : (double)want;
      const double re = ad / (aw > 1.0 ? aw : 1.0);
      if (ad > max_abs_err) max_abs_err = ad;
      if (re > max_rel_err) max_rel_err = re;
      n_compared++;
    }
  }
}

int main(void) {
  // mstatus.XS = Dirty, or every custom0 instruction below traps as illegal.
  nvfp4_enable();

  // The fused global scale, g = fp32(s2A * s2B), rounded HERE on the host
  // because the exact product of two fp32 values needs up to 48 mantissa bits
  // and simply does not fit SET_GSCALE's 32-bit field (section 3.5.1).
  // MVOUT_RAW does not apply g -- it is loaded anyway so the dispatch is the
  // real section 4.4 sequence and so a later MVOUT test needs no new setup.
  const uint32_t g_bits = nvfp4_fuse_gscale(layer_a_ws2_bits, layer_b_ws2_bits);

  for (int i = 0; i < LAYER_M * LAYER_N; i++) {
    layer_out[i] = 0;
  }

  // ---- once per dispatch (section 4.4) ----
  // M_tiles/N_tiles/K_blocks describe what ONE COMPUTE consumes. That is the
  // reading the RTL settled on for K_blocks (the per-COMPUTE count comes from
  // rs1's A_blocks field and CONFIG_EX's copy is latched for readback only),
  // and the shape fields are kept consistent with it rather than describing
  // the whole 4x256x2048 dispatch.
  nvfp4_config_ex(LAYER_M, NVFP4_N_PE, KB_PER_COMPUTE, NVFP4_ACT_NONE, 0);
  // Destination row stride: the full output row, LAYER_N*8 bytes, NOT the
  // tile's 16*8. This is what lets one 4x16 MVOUT_RAW land as a sub-rectangle
  // of the [LAYER_M][LAYER_N] buffer.
  nvfp4_config_st((uint32_t)(LAYER_N * (int)sizeof(int64_t)), NVFP4_ACT_NONE,
                  NVFP4_OUT_FP32);
  nvfp4_set_gscale(g_bits, NULL);

  // Mandatory before handing CPU-written buffers to the accelerator: the
  // output buffer was just zeroed by the core and the engine's own memory port
  // is not coherent with the core's store buffer.
  nvfp4_fence();

  const uint64_t t0 = rdcycle();
  const uint64_t busy0 = nvfp4_counter(NVFP4_COUNTER_CYCLES);

  int t = 0;
  for (int n0 = 0; n0 < LAYER_N; n0 += NVFP4_N_PE, t++) {
    const uint64_t tb0 = nvfp4_counter(NVFP4_COUNTER_CYCLES);
    run_tile(n0);
    const uint64_t tb1 = nvfp4_counter(NVFP4_COUNTER_CYCLES);
    tile_busy[t] = tb1 - tb0;
  }

  // Read the aggregate after the last FLUSH so it includes every dispatch.
  const uint64_t busy1 = nvfp4_counter(NVFP4_COUNTER_CYCLES);

  // Drain before the core reads the result back.
  nvfp4_fence();
  const uint64_t t1 = rdcycle();

  for (int i = 0; i < N_TILES; i++) {
    printf("nvfp4_layer: tile %2d n0=%3d acc_cycles=%lu\n",
           i, i * NVFP4_N_PE, (unsigned long)tile_busy[i]);
  }
  printf("nvfp4_layer: M=%d N=%d K=%d tiles=%d chunks/tile=%d "
         "blocks/compute=%d total_acc_cycles=%lu g=0x%08lx\n",
         LAYER_M, LAYER_N, LAYER_K, N_TILES, K_CHUNKS, KB_PER_COMPUTE,
         (unsigned long)(busy1 - busy0), (unsigned long)g_bits);

  check_all();

  printf("nvfp4_layer: exact matches %d/%d\n",
         n_compared - n_mismatch, n_compared);

  // Sticky error bits (clamped tile shape, spad overflow, unimplemented
  // funct7, section 2.4 exponent window). Reported, not folded into the
  // pass/fail decision -- but a nonzero word alongside an exact result still
  // matters and must not be lost.
  const uint64_t errs = nvfp4_counter(NVFP4_COUNTER_ERRORS);
  printf("nvfp4_layer: sticky error bits = 0x%lx\n", (unsigned long)errs);

  // max_abs_err is an EXACT integer accumulator difference in 2^-20 LSBs. On a
  // correct engine it is 0 and there is no tolerance to fall back on.
  printf("=== MODELBLASTER_VERIFY === max_abs_err=%.9g max_rel_err=%.9g n=%d\n",
         max_abs_err, max_rel_err, n_compared);
  // Wall cycles cover the dispatch loop only; the printf and compare loops are
  // outside it on purpose, so this number is comparable to total_acc_cycles.
  printf("=== MODELBLASTER_WALL_CYCLES === %lu\n",
         (unsigned long)(t1 - t0));

  return n_mismatch == 0 ? 0 : 1;
}
