package pdmmic

import chisel3._
import chisel3.experimental.IntParam
import org.chipsalliance.cde.config.{Config, Field, Parameters}
import freechips.rocketchip.subsystem.{BaseSubsystem, PBUS}
import freechips.rocketchip.diplomacy._
import freechips.rocketchip.prci._
import freechips.rocketchip.regmapper.{RegField, RegReadFn, RegWriteFn}
import freechips.rocketchip.tilelink._

/** SoC-level parameters for the PYNQ-Z1's PDM microphone front end.
  *
  * The defaults are not arbitrary: they are what makes the chain land on 15993.859 Hz
  * from a 34.482759 MHz (1000/29) FCLK0, and they must agree with the coefficient table
  * generated by fpga/pynq-z2/rtl_study/pdm/gen_fir.py.  Changing cicR, firTaps, firDecim
  * or firShift here WITHOUT regenerating that table silently changes the filter's gain
  * and its stopband.  See fpga/pynq-z2/docs/MICROPHONE.md.
  */
case class PdmMicParams(
  address:     BigInt = 0x10090000L,
  pdmHalf:     Int    = 7,        // system clocks per PDM half period -> 2.463054 MHz
  cicR:        Int    = 22,       // CIC decimation  -> 111.957 kHz
  firTaps:     Int    = 289,
  firDecim:    Int    = 7,        // FIR decimation  -> 15993.859 Hz
  firShift:    Int    = 22,
  settle:      Int    = 131072,   // PDM bits discarded after enable (53 ms)
  fifoLog2:    Int    = 10,       // 1024 samples = 64 ms
  rateMilliHz: BigInt = BigInt(15993859)
)

case object PdmMicKey extends Field[Option[PdmMicParams]](None)

/** The two off-chip pins.  F17 and G18 on the PYNQ-Z1; see MICROPHONE.md s1.3.
  * There is no third pin: the microphone's L/R SELECT is tied low on the board.
  */
class PdmMicIO extends Bundle {
  val pdm_clk  = Output(Bool())   // -> F17, the clock we generate for the microphone
  val pdm_data = Input(Bool())    // <- G18, the returned 1-bit bitstream
}

/** Black box around fpga/pynq-z2/src/pdm_mic_core.v.
  *
  * Deliberately a plain BlackBox (a FIRRTL extmodule) rather than a
  * HasBlackBoxResource: the Verilog stays in exactly ONE place, this repo's src/, where
  * sim/run_pdm_sim.sh already tests it, and tcl/build_rocket.tcl adds it to the project
  * the same way it already adds pynqz2_rocket_top.v and soc_ctrl_regs.v.  Copying it
  * into the generator's resources would make three copies that can drift.
  */
class pdm_mic_core(params: PdmMicParams) extends BlackBox(Map(
  "PDM_HALF"   -> IntParam(params.pdmHalf),
  "CIC_R"      -> IntParam(params.cicR),
  "FIR_TAPS"   -> IntParam(params.firTaps),
  "FIR_DECIM"  -> IntParam(params.firDecim),
  "FIR_SHIFT"  -> IntParam(params.firShift),
  "SETTLE"     -> IntParam(params.settle),
  "FIFO_ALOG2" -> IntParam(params.fifoLog2),
  "RATE_MHZ"   -> IntParam(params.rateMilliHz)
)) {
  val io = IO(new Bundle {
    val clk        = Input(Clock())
    val rst        = Input(Bool())
    val pdm_m_clk  = Output(Bool())
    val pdm_m_data = Input(Bool())
    val reg_addr   = Input(UInt(4.W))
    val reg_wr     = Input(Bool())
    val reg_wdata  = Input(UInt(32.W))
    val reg_rd     = Input(Bool())
    val reg_rdata  = Output(UInt(32.W))
    val irq        = Output(Bool())
  })
}

/** TileLink MMIO wrapper.
  *
  * Register map, as the CPU sees it.  ONE 32-BIT REGISTER PER 64-BIT BUS WORD, which is
  * why the stride is 8 and not 4.  The black box has a single shared `reg_addr` port, so
  * if two fields shared a bus word an 8-byte access would raise both their `ivalid`s and
  * the address mux below would be ambiguous.  A 4 KB page holds eight registers eight
  * bytes apart with room to spare, so the cheap fix is the right one.
  *
  *   0x00 ID      R   0x504D4331 "PMC1"
  *   0x08 CTRL    RW  [0] enable [1] fifo_reset [2] dc_bypass [3] clear_sticky
  *   0x10 STATUS  R   [0] settling [1] empty [2] full [3] overrun [4] saturated
  *   0x18 LEVEL   R   samples available
  *   0x20 DATA    R   pops one sample, sign-extended
  *   0x28 RATE    R   PCM rate in MILLIHERTZ (15993859)
  *   0x30 DEPTH   R   FIFO depth in samples
  *   0x38 WMARK   RW  interrupt watermark
  *
  * NO INTERRUPT NODE, on purpose.  This SoC's PLIC has exactly one source -- the UART,
  * `riscv,ndev = <1>` -- and adding a second renumbers nothing but does change ndev and
  * the generated DTS that boards/chipyard/pynqz1_pext transcribes.  At 16 kHz x 2 bytes
  * with a 64 ms FIFO there is nothing an interrupt buys, so the black box's `irq` output
  * is left unread and the driver polls.  That keeps the console's interrupt wiring
  * byte-identical to the config this one is derived from.
  */
class PdmMic(params: PdmMicParams, beatBytes: Int)(implicit p: Parameters)
    extends ClockSinkDomain(ClockSinkParameters())(p) {
  val device = new SimpleDevice("pdm-mic", Seq("iiswc,pdm-mic"))
  val node = TLRegisterNode(
    Seq(AddressSet(params.address, 4096 - 1)),
    device,
    "reg/control",
    beatBytes = beatBytes)

  override lazy val module = new PdmMicImpl
  class PdmMicImpl extends Impl {
    val io = IO(new PdmMicIO)

    withClockAndReset(clock, reset) {
      val core = Module(new pdm_mic_core(params))
      core.io.clk := clock
      core.io.rst := reset.asBool

      io.pdm_clk         := core.io.pdm_m_clk
      core.io.pdm_m_data := io.pdm_data

      // The black box presents a bus-agnostic single-cycle register port; these wires are
      // the whole of the TileLink glue.
      val regAddr  = WireDefault(0.U(4.W))
      val regRd    = WireDefault(false.B)
      val regWr    = WireDefault(false.B)
      val regWdata = WireDefault(0.U(32.W))
      core.io.reg_addr  := regAddr
      core.io.reg_rd    := regRd
      core.io.reg_wr    := regWr
      core.io.reg_wdata := regWdata

      // `reg_rd` must pulse EXACTLY ONCE per completed read, because reading DATA pops the
      // FIFO.  Both of these use RegReadFn/RegWriteFn's COMBINATIONAL forms -- the
      // one-argument `oready => (ovalid, data)` and two-argument `(oready, data) => ready`
      // overloads -- and that choice is load-bearing twice over.
      //
      // First, the two-argument read form sets `combinational = false`, which makes
      // RegMapper's `pipelined` true and then fails the requirement
      //   "Register-based device with request/response handshaking needs concurrency > 0"
      // at elaboration.  Raising concurrency would work but puts a queue between the
      // request and the response, so the address driven at request time is gone by the
      // time the data is sampled, and the read would have to be latched.
      //
      // Second, the combinational form's argument is exactly the signal wanted:
      // RegMapper computes it as `roready(i) && romask`, and with every f_rovalid a
      // literal true that reduces to "this field's read is completing in this cycle".
      // RegMapper only samples `out.bits.data` in that cycle (out.valid is itself gated on
      // it), so driving the shared address mux from it is safe, and there is no
      // combinational loop: oready depends on out.ready and on the literal valids, never
      // on the data.
      def rd(idx: Int) = RegReadFn((oready: Bool) => {
        when (oready) { regAddr := idx.U; regRd := true.B }
        (true.B, core.io.reg_rdata)
      })
      def wr(idx: Int) = RegWriteFn((woready: Bool, data: UInt) => {
        when (woready) { regAddr := idx.U; regWdata := data; regWr := true.B }
        true.B
      })

      node.regmap(
        0x00 -> Seq(RegField.r(32, rd(0))),          // ID
        0x08 -> Seq(RegField  (32, rd(1), wr(1))),   // CTRL
        0x10 -> Seq(RegField.r(32, rd(2))),          // STATUS
        0x18 -> Seq(RegField.r(32, rd(3))),          // LEVEL
        0x20 -> Seq(RegField.r(32, rd(4))),          // DATA -- reading pops
        0x28 -> Seq(RegField.r(32, rd(5))),          // RATE
        0x30 -> Seq(RegField.r(32, rd(6))),          // DEPTH
        0x38 -> Seq(RegField  (32, rd(7), wr(7)))    // WMARK
      )
    }
  }
}

/** Mix into the SoC to optionally instantiate the PDM microphone. */
trait CanHavePeripheryPdmMic { this: BaseSubsystem =>
  private val portName = "pdmmic"
  private val pbus = locateTLBusWrapper(PBUS)

  val pdm_mic = p(PdmMicKey).map { params =>
    val micLM = LazyModule(new PdmMic(params, pbus.beatBytes)(p))
    micLM.clockNode := pbus.fixedClockNode
    pbus.coupleTo(portName) {
      TLInwardClockCrossingHelper(s"${portName}_crossing", micLM, micLM.node)(SynchronousCrossing()) :=
      TLFragmenter(pbus.beatBytes, pbus.blockBytes) := _
    }

    InModuleBody {
      val pins = IO(chiselTypeOf(micLM.module.io)).suggestName("mic")
      pins <> micLM.module.io
      pins
    }
  }
}

/** Config fragment: enable the PDM microphone peripheral. */
class WithPdmMic(address: BigInt = 0x10090000L) extends Config((site, here, up) => {
  case PdmMicKey => Some(PdmMicParams(address = address))
})
