// auto-generated by fc_rocc_asm.c
localparam int ROMD=926, EST_START=0, CTRL_START=537, NREGP=256;
localparam int IN_AX=6,IN_AY=7,IN_AZ=8,IN_GX=9,IN_GY=10,IN_GZ=11,IN_F0=12,IN_F1=13,IN_H=14,IN_DT=15,IN_FV=16,IN_TV=17,IN_DESH=18,IN_DESV1=19,IN_DESV2=20,IN_YAWT=21;
localparam int U0=56,U1=57,U2=58,U3=59;
localparam int SOUT [0:11] = '{44,45,46,47,48,49,50,51,52,53,54,55};
